# Generated by Django 5.2.5 on 2025-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('overall_satisfaction', models.CharField(max_length=10)),
                ('product_quality', models.IntegerField()),
                ('delivery_service_rating', models.IntegerField()),
                ('recommendation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=10)),
                ('additional_feedback', models.TextField(blank=True)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
